// <auto-generated />
using System;
using LQV_BlockchainCertificate.Models.DBModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LQV_BlockchainCertificate.Migrations
{
    [DbContext(typeof(LqvDbContext))]
    partial class LqvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBaiLam", b =>
                {
                    b.Property<int>("LqvBaiLamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_BaiLamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvBaiLamId"));

                    b.Property<double?>("LqvDiem")
                        .HasColumnType("float")
                        .HasColumnName("LQV_Diem");

                    b.Property<int>("LqvLichThiId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_LichThiID");

                    b.Property<DateTime?>("LqvThoiGianBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGianBatDau");

                    b.Property<DateTime?>("LqvThoiGianNop")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGianNop");

                    b.Property<string>("LqvTrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LQV_TrangThai");

                    b.Property<int>("LqvUserId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_UserID");

                    b.Property<bool>("Lqv_BiKhoa")
                        .HasColumnType("bit");

                    b.Property<int>("Lqv_TongDiemRisk")
                        .HasColumnType("int");

                    b.HasKey("LqvBaiLamId")
                        .HasName("PK__LQV_BaiL__55B63CF62DCD3DE8");

                    b.HasIndex("LqvLichThiId");

                    b.HasIndex("LqvUserId");

                    b.ToTable("LQV_BaiLam", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBaiTap", b =>
                {
                    b.Property<int>("LqvBaiTapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_BaiTapID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvBaiTapId"));

                    b.Property<int>("LqvGiangVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_GiangVienID");

                    b.Property<DateTime>("LqvHanNop")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_HanNop");

                    b.Property<int>("LqvLopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_LopHocID");

                    b.Property<string>("LqvMoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_MoTa");

                    b.Property<DateTime>("LqvNgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LqvTieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LQV_TieuDe");

                    b.Property<string>("LqvTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang mở")
                        .HasColumnName("LQV_TrangThai");

                    b.HasKey("LqvBaiTapId")
                        .HasName("PK__LQV_BaiT__57AA0AE6773421D4");

                    b.HasIndex("LqvGiangVienId");

                    b.HasIndex("LqvLopHocId");

                    b.ToTable("LQV_BaiTap", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBoCauHoi", b =>
                {
                    b.Property<int>("LqvBoCauHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_BoCauHoiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvBoCauHoiId"));

                    b.Property<int>("LqvGiangVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_GiangVienID");

                    b.Property<string>("LqvMoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LQV_MoTa");

                    b.Property<DateTime?>("LqvNgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LqvTenBo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LQV_TenBo");

                    b.HasKey("LqvBoCauHoiId")
                        .HasName("PK__LQV_BoCa__FA85F35FF7B94957");

                    b.HasIndex("LqvGiangVienId");

                    b.ToTable("LQV_BoCauHoi", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBuoiHoc", b =>
                {
                    b.Property<int>("LqvBuoiHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_BuoiHocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvBuoiHocId"));

                    b.Property<double?>("LqvBanKinh")
                        .HasColumnType("float");

                    b.Property<bool>("LqvDangMo")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("LqvGioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("LQV_GioBatDau");

                    b.Property<TimeOnly?>("LqvGioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("LQV_GioKetThuc");

                    b.Property<double?>("LqvKinhDo")
                        .HasColumnType("float");

                    b.Property<int>("LqvLopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_LopHocID");

                    b.Property<DateOnly>("LqvNgayHoc")
                        .HasColumnType("date")
                        .HasColumnName("LQV_NgayHoc");

                    b.Property<double?>("LqvViDo")
                        .HasColumnType("float");

                    b.HasKey("LqvBuoiHocId")
                        .HasName("PK__LQV_Buoi__BB4D0D02FBC7D9BA");

                    b.HasIndex("LqvLopHocId");

                    b.ToTable("LQV_BuoiHoc", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvCauHoi", b =>
                {
                    b.Property<int>("LqvCauHoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_CauHoiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvCauHoiId"));

                    b.Property<int>("LqvBoCauHoiId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_BoCauHoiID");

                    b.Property<double>("LqvDiem")
                        .HasColumnType("float")
                        .HasColumnName("LQV_Diem");

                    b.Property<string>("LqvLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LQV_Loai");

                    b.Property<string>("LqvNoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_NoiDung");

                    b.HasKey("LqvCauHoiId")
                        .HasName("PK__LQV_CauH__495F3E4088D9713D");

                    b.HasIndex("LqvBoCauHoiId");

                    b.ToTable("LQV_CauHoi", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvChiTietBaiLam", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<int>("LqvBaiLamId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_BaiLamID");

                    b.Property<int>("LqvCauHoiId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_CauHoiID");

                    b.Property<bool>("LqvDaCham")
                        .HasColumnType("bit")
                        .HasColumnName("LQV_DaCham");

                    b.Property<int?>("LqvDapAnId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_DapAnID");

                    b.Property<double?>("LqvDiem")
                        .HasColumnType("float")
                        .HasColumnName("LQV_Diem");

                    b.Property<string>("LqvTraLoiTuLuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_TraLoiTuLuan");

                    b.HasKey("LqvId")
                        .HasName("PK__LQV_ChiT__399ABF83E2F36458");

                    b.HasIndex("LqvCauHoiId");

                    b.HasIndex("LqvDapAnId");

                    b.HasIndex(new[] { "LqvBaiLamId", "LqvCauHoiId" }, "UQ_BaiLam_CauHoi")
                        .IsUnique();

                    b.ToTable("LQV_ChiTietBaiLam", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvChucNang", b =>
                {
                    b.Property<int>("LqvChucNangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ChucNangID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvChucNangId"));

                    b.Property<string>("LqvDuongDan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LQV_DuongDan");

                    b.Property<string>("LqvMoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LQV_MoTa");

                    b.Property<string>("LqvTenChucNang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("LQV_TenChucNang");

                    b.HasKey("LqvChucNangId")
                        .HasName("PK__LQV_Chuc__FAAD8ABC81797BAC");

                    b.ToTable("LQV_ChucNang", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvChungNhan", b =>
                {
                    b.Property<int>("LqvMaChungNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_MaChungNhan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvMaChungNhan"));

                    b.Property<string>("LqvHashValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("LQV_HashValue");

                    b.Property<int>("LqvKhoaHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_KhoaHocID");

                    b.Property<string>("LqvMaChungNhanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LQV_MaChungNhanCode");

                    b.Property<DateTime>("LqvNgayCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayCap")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LqvSinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_SinhVienID");

                    b.Property<string>("LqvTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa ghi chain")
                        .HasColumnName("LQV_TrangThai");

                    b.HasKey("LqvMaChungNhan")
                        .HasName("PK__LQV_Chun__7C61D26828A303A5");

                    b.HasIndex("LqvKhoaHocId");

                    b.HasIndex("LqvSinhVienId");

                    b.HasIndex(new[] { "LqvMaChungNhanCode" }, "IX_LQV_ChungNhan_Code");

                    b.HasIndex(new[] { "LqvMaChungNhanCode" }, "UQ__LQV_Chun__98F37C26981B1A53")
                        .IsUnique();

                    b.ToTable("LQV_ChungNhan", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDangKyLopHoc", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<int>("LqvLopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_LopHocID");

                    b.Property<DateTime?>("LqvNgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayDangKy")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LqvSinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_SinhVienID");

                    b.HasKey("LqvId")
                        .HasName("PK__LQV_Dang__399ABF83B02B29EE");

                    b.HasIndex("LqvLopHocId");

                    b.HasIndex("LqvSinhVienId");

                    b.ToTable("LQV_DangKyLopHoc", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDapAn", b =>
                {
                    b.Property<int>("LqvDapAnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_DapAnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvDapAnId"));

                    b.Property<int>("LqvCauHoiId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_CauHoiID");

                    b.Property<bool>("LqvDung")
                        .HasColumnType("bit")
                        .HasColumnName("LQV_Dung");

                    b.Property<string>("LqvNoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_NoiDung");

                    b.HasKey("LqvDapAnId")
                        .HasName("PK__LQV_DapA__B4CD8321589B8AF6");

                    b.HasIndex("LqvCauHoiId");

                    b.ToTable("LQV_DapAn", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDeThi", b =>
                {
                    b.Property<int>("LqvDeThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_DeThiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvDeThiId"));

                    b.Property<int>("LqvBoCauHoiId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_BoCauHoiID");

                    b.Property<bool>("LqvDaDuyet")
                        .HasColumnType("bit");

                    b.Property<int?>("LqvGiangVienId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LqvNgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("LqvTenDeThi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LQV_TenDeThi");

                    b.Property<int>("LqvThoiGianThi")
                        .HasColumnType("int")
                        .HasColumnName("LQV_ThoiGianThi");

                    b.Property<double>("LqvTongDiem")
                        .HasColumnType("float")
                        .HasColumnName("LQV_TongDiem");

                    b.HasKey("LqvDeThiId")
                        .HasName("PK__LQV_DeTh__B0DB988EF7B75BF7");

                    b.HasIndex("LqvBoCauHoiId");

                    b.HasIndex("LqvGiangVienId");

                    b.ToTable("LQV_DeThi", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDiemDanhGp", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<int>("LqvBuoiHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_BuoiHocID");

                    b.Property<bool>("LqvHopLe")
                        .HasColumnType("bit")
                        .HasColumnName("LQV_HopLe");

                    b.Property<double>("LqvKinhDo")
                        .HasColumnType("float")
                        .HasColumnName("LQV_KinhDo");

                    b.Property<int>("LqvLopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_LopHocID");

                    b.Property<int>("LqvSinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_SinhVienID");

                    b.Property<DateTime>("LqvThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGian")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("LqvViDo")
                        .HasColumnType("float")
                        .HasColumnName("LQV_ViDo");

                    b.HasKey("LqvId")
                        .HasName("PK__LQV_Diem__399ABF83D79FEFCB");

                    b.HasIndex("LqvBuoiHocId");

                    b.HasIndex("LqvLopHocId");

                    b.HasIndex("LqvSinhVienId");

                    b.ToTable("LQV_DiemDanhGPS", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvGiaoDichBlockchain", b =>
                {
                    b.Property<int>("LqvMaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_MaGiaoDich");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvMaGiaoDich"));

                    b.Property<long?>("LqvBlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("LQV_BlockNumber");

                    b.Property<int>("LqvChungNhanId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_ChungNhanID");

                    b.Property<DateTime>("LqvGioTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_GioTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LqvNoiDungHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LqvStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("LQV_Status");

                    b.Property<string>("LqvTxHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LQV_TxHash");

                    b.Property<string>("LqvUrlEtherscan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LqvMaGiaoDich")
                        .HasName("PK__LQV_Giao__001ACB4ED5CAC3C4");

                    b.HasIndex("LqvChungNhanId");

                    b.HasIndex(new[] { "LqvTxHash" }, "IX_LQV_GiaoDich_TxHash");

                    b.ToTable("LQV_GiaoDichBlockchain", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvKhoaHoc", b =>
                {
                    b.Property<int>("LqvMaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_MaKhoaHoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvMaKhoaHoc"));

                    b.Property<int?>("LqvGiangVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_GiangVienID");

                    b.Property<string>("LqvMoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("LQV_MoTa");

                    b.Property<DateTime?>("LqvNgayBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayBatDau");

                    b.Property<DateTime?>("LqvNgayKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayKetThuc");

                    b.Property<string>("LqvTenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LQV_TenKhoaHoc");

                    b.HasKey("LqvMaKhoaHoc")
                        .HasName("PK__LQV_Khoa__00BA6E76ACA376DC");

                    b.HasIndex("LqvGiangVienId");

                    b.ToTable("LQV_KhoaHoc", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvLichThi", b =>
                {
                    b.Property<int>("LqvLichThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_LichThiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvLichThiId"));

                    b.Property<DateTime>("LqvBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_BatDau");

                    b.Property<int>("LqvDeThiId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_DeThiID");

                    b.Property<DateTime>("LqvKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_KetThuc");

                    b.Property<int>("LqvLopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_LopHocID");

                    b.HasKey("LqvLichThiId")
                        .HasName("PK__LQV_Lich__76CDCC5C5CE45949");

                    b.HasIndex("LqvDeThiId");

                    b.HasIndex("LqvLopHocId");

                    b.ToTable("LQV_LichThi", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", b =>
                {
                    b.Property<int>("LqvLopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_LopHocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvLopHocId"));

                    b.Property<int>("LqvGiangVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_GiangVienID");

                    b.Property<int>("LqvKhoaHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_KhoaHocID");

                    b.Property<string>("LqvMoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("LQV_MoTa");

                    b.Property<DateTime?>("LqvNgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LqvTenLop")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LQV_TenLop");

                    b.HasKey("LqvLopHocId")
                        .HasName("PK__LQV_LopH__B68A262EA6901F01");

                    b.HasIndex("LqvGiangVienId");

                    b.HasIndex("LqvKhoaHocId");

                    b.ToTable("LQV_LopHoc", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<string>("LqvAvt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LqvDaXacThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("LQV_DaXacThuc");

                    b.Property<string>("LqvEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("LQV_Email");

                    b.Property<string>("LqvHoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("LQV_HoTen");

                    b.Property<string>("LqvMatKhauHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("LQV_MatKhauHash");

                    b.Property<DateTime?>("LqvNgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LqvNgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LqvRoleId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_RoleID");

                    b.Property<string>("LqvTenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LQV_TenDangNhap");

                    b.Property<string>("LqvWalletAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LQV_WalletAddress");

                    b.HasKey("LqvId")
                        .HasName("PK__LQV_Nguo__399ABF836CDD5D3E");

                    b.HasIndex("LqvRoleId");

                    b.HasIndex(new[] { "LqvWalletAddress" }, "IX_LQV_NguoiDung_Wallet");

                    b.ToTable("LQV_NguoiDung", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvNhatKyHoatDong", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<string>("LqvChiTiet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_ChiTiet");

                    b.Property<string>("LqvHanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LQV_HanhDong");

                    b.Property<string>("LqvIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LQV_Ip");

                    b.Property<string>("LqvTaiKhoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LQV_TaiKhoan");

                    b.Property<DateTime?>("LqvThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGian")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LqvId")
                        .HasName("PK__LQV_Nhat__399ABFA3BAA56476");

                    b.ToTable("LQV_NhatKyHoatDong", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvNopBaiTap", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<int>("LqvBaiTapId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_BaiTapID");

                    b.Property<bool>("LqvDaCham")
                        .HasColumnType("bit")
                        .HasColumnName("LQV_DaCham");

                    b.Property<double?>("LqvDiem")
                        .HasColumnType("float")
                        .HasColumnName("LQV_Diem");

                    b.Property<string>("LqvFile")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LQV_File");

                    b.Property<string>("LqvNhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_NhanXet");

                    b.Property<string>("LqvNoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_NoiDung");

                    b.Property<int>("LqvSinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_SinhVienID");

                    b.Property<DateTime>("LqvThoiGianNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGianNop")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LqvId")
                        .HasName("PK__LQV_NopB__399ABF83B2BDB053");

                    b.HasIndex("LqvSinhVienId");

                    b.HasIndex(new[] { "LqvBaiTapId", "LqvSinhVienId" }, "UQ_NopBai")
                        .IsUnique();

                    b.ToTable("LQV_NopBaiTap", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvPhanQuyen", b =>
                {
                    b.Property<int>("LqvPhanQuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_PhanQuyenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvPhanQuyenId"));

                    b.Property<bool>("LqvChoPhep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("LQV_ChoPhep");

                    b.Property<int>("LqvChucNangId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_ChucNangID");

                    b.Property<int>("LqvRoleId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_RoleID");

                    b.HasKey("LqvPhanQuyenId")
                        .HasName("PK__LQV_Phan__511351DF0E3ADF8F");

                    b.HasIndex("LqvChucNangId");

                    b.HasIndex("LqvRoleId");

                    b.ToTable("LQV_PhanQuyen", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvRole", b =>
                {
                    b.Property<int>("LqvRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvRoleId"));

                    b.Property<string>("LqvRoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LQV_RoleName");

                    b.HasKey("LqvRoleId")
                        .HasName("PK__LQV_Role__1C56210837B04E10");

                    b.HasIndex(new[] { "LqvRoleName" }, "UQ__LQV_Role__2D9D26F63B2DA1B8")
                        .IsUnique();

                    b.ToTable("LQV_Role", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvTienDoHocTap", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<int>("LqvKhoaHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_KhoaHocId");

                    b.Property<DateTime?>("LqvNgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("LQV_NgayCapNhat")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LqvSinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_SinhVienId");

                    b.Property<double>("LqvTiLeHoanThanh")
                        .HasColumnType("float")
                        .HasColumnName("LQV_TiLeHoanThanh");

                    b.HasKey("LqvId");

                    b.HasIndex(new[] { "LqvKhoaHocId" }, "IX_LQV_TienDoHocTap_KhoaHocID");

                    b.HasIndex(new[] { "LqvSinhVienId" }, "IX_LQV_TienDoHocTap_SinhVienID");

                    b.HasIndex(new[] { "LqvSinhVienId", "LqvKhoaHocId" }, "UQ_LQV_TienDoHocTap_SinhVien_KhoaHoc")
                        .IsUnique();

                    b.ToTable("LQV_TienDoHocTap", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvXacThucChungNhan", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<string>("LqvDiaChiNguoiXacThuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LQV_DiaChiNguoiXacThuc");

                    b.Property<string>("LqvKetQua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LQV_KetQua");

                    b.Property<string>("LqvMaChungNhanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LQV_MaChungNhanCode");

                    b.Property<DateTime>("LqvThoiGianXacThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGianXacThuc")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LqvId")
                        .HasName("PK__LQV_XacT__399ABF8304A8D876");

                    b.HasIndex(new[] { "LqvMaChungNhanCode" }, "IX_LQV_XacThuc_MaCert");

                    b.ToTable("LQV_XacThucChungNhan", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvXacThucEmail", b =>
                {
                    b.Property<int>("LqvMaXacThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_MaXacThuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvMaXacThuc"));

                    b.Property<string>("LqvEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("LQV_Email");

                    b.Property<string>("LqvLoaiXacThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LQV_LoaiXacThuc");

                    b.Property<string>("LqvMaOtp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LQV_MaOTP");

                    b.Property<DateTime>("LqvThoiGianHetHan")
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGianHetHan");

                    b.Property<DateTime>("LqvThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGianTao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("LqvTrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("LQV_TrangThai");

                    b.HasKey("LqvMaXacThuc")
                        .HasName("PK__LQV_XacT__04AC4BAE82B51BB4");

                    b.ToTable("LQV_XacThucEmail", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvYeuCauCapChungChi", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<int?>("LqvChungNhanId")
                        .HasColumnType("int");

                    b.Property<int>("LqvKhoaHocId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_KhoaHocID");

                    b.Property<string>("LqvLyDoTuChoi")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LqvLyDoYeuCau")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("LQV_LyDoYeuCau");

                    b.Property<DateTime?>("LqvNgayYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_NgayYeuCau")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("LqvNguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_NguoiDungID");

                    b.Property<string>("LqvTrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ duyệt")
                        .HasColumnName("LQV_TrangThai");

                    b.HasKey("LqvId");

                    b.HasIndex("LqvChungNhanId");

                    b.HasIndex(new[] { "LqvKhoaHocId" }, "IX_LQV_YeuCauCapChungChi_LQV_KhoaHocID");

                    b.HasIndex(new[] { "LqvNguoiDungId" }, "IX_LQV_YeuCauCapChungChi_LQV_NguoiDungID");

                    b.ToTable("LQV_YeuCauCapChungChi", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvYeuCauHoTro", b =>
                {
                    b.Property<int>("LqvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LQV_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LqvId"));

                    b.Property<int>("LqvNguoiDungId")
                        .HasColumnType("int")
                        .HasColumnName("LQV_NguoiDungID");

                    b.Property<string>("LqvNoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_NoiDung");

                    b.Property<string>("LqvPhanHoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LQV_PhanHoi");

                    b.Property<DateTime?>("LqvThoiGianGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("LQV_ThoiGianGui")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LqvTrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Mới")
                        .HasColumnName("LQV_TrangThai");

                    b.HasKey("LqvId");

                    b.HasIndex(new[] { "LqvNguoiDungId" }, "IX_LQV_YeuCauHoTro_LQV_NguoiDungID");

                    b.ToTable("LQV_YeuCauHoTro", (string)null);
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.Lqv_NhatKyHinhAnhThi", b =>
                {
                    b.Property<int>("Lqv_NhatKyHinhAnhThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lqv_NhatKyHinhAnhThiId"));

                    b.Property<int>("Lqv_BaiLamId")
                        .HasColumnType("int");

                    b.Property<string>("Lqv_DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lqv_KetQuaAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lqv_ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Lqv_NhatKyHinhAnhThiId");

                    b.HasIndex("Lqv_BaiLamId");

                    b.ToTable("Lqv_NhatKyHinhAnhThi");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.Lqv_NhatKyViPhamThi", b =>
                {
                    b.Property<int>("Lqv_NhatKyViPhamThiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lqv_NhatKyViPhamThiId"));

                    b.Property<int>("Lqv_BaiLamId")
                        .HasColumnType("int");

                    b.Property<int>("Lqv_DiemRisk")
                        .HasColumnType("int");

                    b.Property<string>("Lqv_LoaiViPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lqv_MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Lqv_ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Lqv_NhatKyViPhamThiId");

                    b.HasIndex("Lqv_BaiLamId");

                    b.ToTable("Lqv_NhatKyViPhamThi");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBaiLam", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvLichThi", "LqvLichThi")
                        .WithMany()
                        .HasForeignKey("LqvLichThiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvNguoiDung")
                        .WithMany()
                        .HasForeignKey("LqvUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LqvLichThi");

                    b.Navigation("LqvNguoiDung");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBaiTap", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvGiangVien")
                        .WithMany("LqvBaiTaps")
                        .HasForeignKey("LqvGiangVienId")
                        .IsRequired()
                        .HasConstraintName("FK_BaiTap_GiangVien");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", "LqvLopHoc")
                        .WithMany("LqvBaiTaps")
                        .HasForeignKey("LqvLopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_BaiTap_LopHoc");

                    b.Navigation("LqvGiangVien");

                    b.Navigation("LqvLopHoc");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBoCauHoi", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvGiangVien")
                        .WithMany("LqvBoCauHois")
                        .HasForeignKey("LqvGiangVienId")
                        .IsRequired()
                        .HasConstraintName("FK_BoCauHoi_GiangVien");

                    b.Navigation("LqvGiangVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBuoiHoc", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", "LqvLopHoc")
                        .WithMany("LqvBuoiHocs")
                        .HasForeignKey("LqvLopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LqvLopHoc");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvCauHoi", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvBoCauHoi", "LqvBoCauHoi")
                        .WithMany("LqvCauHois")
                        .HasForeignKey("LqvBoCauHoiId")
                        .IsRequired()
                        .HasConstraintName("FK_CauHoi_Bo");

                    b.Navigation("LqvBoCauHoi");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvChiTietBaiLam", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvBaiLam", "LqvBaiLam")
                        .WithMany("LqvChiTietBaiLams")
                        .HasForeignKey("LqvBaiLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietBaiLam_BaiLam");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvCauHoi", "LqvCauHoi")
                        .WithMany("LqvChiTietBaiLams")
                        .HasForeignKey("LqvCauHoiId")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietBaiLam_CauHoi");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvDapAn", "LqvDapAn")
                        .WithMany("LqvChiTietBaiLams")
                        .HasForeignKey("LqvDapAnId")
                        .HasConstraintName("FK_ChiTietBaiLam_DapAn");

                    b.Navigation("LqvBaiLam");

                    b.Navigation("LqvCauHoi");

                    b.Navigation("LqvDapAn");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvChungNhan", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvKhoaHoc", "LqvKhoaHoc")
                        .WithMany("LqvChungNhans")
                        .HasForeignKey("LqvKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_ChungNhan_KhoaHoc");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvSinhVien")
                        .WithMany("LqvChungNhans")
                        .HasForeignKey("LqvSinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_ChungNhan_SinhVien");

                    b.Navigation("LqvKhoaHoc");

                    b.Navigation("LqvSinhVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDangKyLopHoc", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", "LqvLopHoc")
                        .WithMany("LqvDangKyLopHocs")
                        .HasForeignKey("LqvLopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_DK_LopHoc");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvSinhVien")
                        .WithMany("LqvDangKyLopHocs")
                        .HasForeignKey("LqvSinhVienId")
                        .IsRequired()
                        .HasConstraintName("FK_DK_SinhVien");

                    b.Navigation("LqvLopHoc");

                    b.Navigation("LqvSinhVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDapAn", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvCauHoi", "LqvCauHoi")
                        .WithMany("LqvDapAns")
                        .HasForeignKey("LqvCauHoiId")
                        .IsRequired()
                        .HasConstraintName("FK_DapAn_CauHoi");

                    b.Navigation("LqvCauHoi");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDeThi", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvBoCauHoi", "LqvBoCauHoi")
                        .WithMany("LqvDeThis")
                        .HasForeignKey("LqvBoCauHoiId")
                        .IsRequired()
                        .HasConstraintName("FK_DeThi_BoCauHoi");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvGiangVien")
                        .WithMany()
                        .HasForeignKey("LqvGiangVienId");

                    b.Navigation("LqvBoCauHoi");

                    b.Navigation("LqvGiangVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDiemDanhGp", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvBuoiHoc", "LqvBuoiHoc")
                        .WithMany("LqvDiemDanhGps")
                        .HasForeignKey("LqvBuoiHocId")
                        .IsRequired()
                        .HasConstraintName("FK_DiemDanh_BuoiHoc");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", "LqvLopHoc")
                        .WithMany("LqvDiemDanhGps")
                        .HasForeignKey("LqvLopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_DiemDanh_LopHoc");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvSinhVien")
                        .WithMany("LqvDiemDanhGps")
                        .HasForeignKey("LqvSinhVienId")
                        .IsRequired()
                        .HasConstraintName("FK_DiemDanh_SinhVien");

                    b.Navigation("LqvBuoiHoc");

                    b.Navigation("LqvLopHoc");

                    b.Navigation("LqvSinhVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvGiaoDichBlockchain", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvChungNhan", "LqvChungNhan")
                        .WithMany("LqvGiaoDichBlockchains")
                        .HasForeignKey("LqvChungNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_GiaoDich_ChungNhan");

                    b.Navigation("LqvChungNhan");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvKhoaHoc", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvGiangVien")
                        .WithMany("LqvKhoaHocs")
                        .HasForeignKey("LqvGiangVienId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_LQV_KhoaHoc_GiangVien");

                    b.Navigation("LqvGiangVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvLichThi", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvDeThi", "LqvDeThi")
                        .WithMany("LqvLichThis")
                        .HasForeignKey("LqvDeThiId")
                        .IsRequired()
                        .HasConstraintName("FK_LichThi_DeThi");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", "LqvLopHoc")
                        .WithMany("LqvLichThis")
                        .HasForeignKey("LqvLopHocId")
                        .IsRequired()
                        .HasConstraintName("FK_LichThi_LopHoc");

                    b.Navigation("LqvDeThi");

                    b.Navigation("LqvLopHoc");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvGiangVien")
                        .WithMany("LqvLopHocs")
                        .HasForeignKey("LqvGiangVienId")
                        .IsRequired()
                        .HasConstraintName("FK_LopHoc_GiangVien");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvKhoaHoc", "LqvKhoaHoc")
                        .WithMany("LqvLopHocs")
                        .HasForeignKey("LqvKhoaHocId")
                        .IsRequired()
                        .HasConstraintName("FK_LopHoc_KhoaHoc");

                    b.Navigation("LqvGiangVien");

                    b.Navigation("LqvKhoaHoc");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvRole", "LqvRole")
                        .WithMany("LqvNguoiDungs")
                        .HasForeignKey("LqvRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_LQV_NguoiDung_Role");

                    b.Navigation("LqvRole");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvNopBaiTap", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvBaiTap", "LqvBaiTap")
                        .WithMany("LqvNopBaiTaps")
                        .HasForeignKey("LqvBaiTapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NopBai_BaiTap");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvSinhVien")
                        .WithMany("LqvNopBaiTaps")
                        .HasForeignKey("LqvSinhVienId")
                        .IsRequired()
                        .HasConstraintName("FK_NopBai_SinhVien");

                    b.Navigation("LqvBaiTap");

                    b.Navigation("LqvSinhVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvPhanQuyen", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvChucNang", "LqvChucNang")
                        .WithMany("LqvPhanQuyens")
                        .HasForeignKey("LqvChucNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_PhanQuyen_ChucNang");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvRole", "LqvRole")
                        .WithMany("LqvPhanQuyens")
                        .HasForeignKey("LqvRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_PhanQuyen_Role");

                    b.Navigation("LqvChucNang");

                    b.Navigation("LqvRole");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvTienDoHocTap", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvKhoaHoc", "LqvKhoaHoc")
                        .WithMany("LqvTienDoHocTaps")
                        .HasForeignKey("LqvKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_TienDoHocTap_KhoaHoc");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvSinhVien")
                        .WithMany("LqvTienDoHocTaps")
                        .HasForeignKey("LqvSinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_TienDoHocTap_NguoiDung");

                    b.Navigation("LqvKhoaHoc");

                    b.Navigation("LqvSinhVien");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvYeuCauCapChungChi", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvChungNhan", "LqvChungNhan")
                        .WithMany()
                        .HasForeignKey("LqvChungNhanId");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvKhoaHoc", "LqvKhoaHoc")
                        .WithMany("LqvYeuCauCapChungChis")
                        .HasForeignKey("LqvKhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_YeuCauCapChungChi_KhoaHoc");

                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvNguoiDung")
                        .WithMany("LqvYeuCauCapChungChis")
                        .HasForeignKey("LqvNguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_YeuCauCapChungChi_NguoiDung");

                    b.Navigation("LqvChungNhan");

                    b.Navigation("LqvKhoaHoc");

                    b.Navigation("LqvNguoiDung");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvYeuCauHoTro", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", "LqvNguoiDung")
                        .WithMany("LqvYeuCauHoTros")
                        .HasForeignKey("LqvNguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LQV_YeuCauHoTro_NguoiDung");

                    b.Navigation("LqvNguoiDung");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.Lqv_NhatKyHinhAnhThi", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvBaiLam", "Lqv_BaiLam")
                        .WithMany("Lqv_NhatKyHinhAnhThis")
                        .HasForeignKey("Lqv_BaiLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lqv_BaiLam");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.Lqv_NhatKyViPhamThi", b =>
                {
                    b.HasOne("LQV_BlockchainCertificate.Models.DBModel.LqvBaiLam", "Lqv_BaiLam")
                        .WithMany("Lqv_NhatKyViPhamThis")
                        .HasForeignKey("Lqv_BaiLamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lqv_BaiLam");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBaiLam", b =>
                {
                    b.Navigation("LqvChiTietBaiLams");

                    b.Navigation("Lqv_NhatKyHinhAnhThis");

                    b.Navigation("Lqv_NhatKyViPhamThis");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBaiTap", b =>
                {
                    b.Navigation("LqvNopBaiTaps");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBoCauHoi", b =>
                {
                    b.Navigation("LqvCauHois");

                    b.Navigation("LqvDeThis");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvBuoiHoc", b =>
                {
                    b.Navigation("LqvDiemDanhGps");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvCauHoi", b =>
                {
                    b.Navigation("LqvChiTietBaiLams");

                    b.Navigation("LqvDapAns");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvChucNang", b =>
                {
                    b.Navigation("LqvPhanQuyens");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvChungNhan", b =>
                {
                    b.Navigation("LqvGiaoDichBlockchains");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDapAn", b =>
                {
                    b.Navigation("LqvChiTietBaiLams");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvDeThi", b =>
                {
                    b.Navigation("LqvLichThis");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvKhoaHoc", b =>
                {
                    b.Navigation("LqvChungNhans");

                    b.Navigation("LqvLopHocs");

                    b.Navigation("LqvTienDoHocTaps");

                    b.Navigation("LqvYeuCauCapChungChis");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvLopHoc", b =>
                {
                    b.Navigation("LqvBaiTaps");

                    b.Navigation("LqvBuoiHocs");

                    b.Navigation("LqvDangKyLopHocs");

                    b.Navigation("LqvDiemDanhGps");

                    b.Navigation("LqvLichThis");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvNguoiDung", b =>
                {
                    b.Navigation("LqvBaiTaps");

                    b.Navigation("LqvBoCauHois");

                    b.Navigation("LqvChungNhans");

                    b.Navigation("LqvDangKyLopHocs");

                    b.Navigation("LqvDiemDanhGps");

                    b.Navigation("LqvKhoaHocs");

                    b.Navigation("LqvLopHocs");

                    b.Navigation("LqvNopBaiTaps");

                    b.Navigation("LqvTienDoHocTaps");

                    b.Navigation("LqvYeuCauCapChungChis");

                    b.Navigation("LqvYeuCauHoTros");
                });

            modelBuilder.Entity("LQV_BlockchainCertificate.Models.DBModel.LqvRole", b =>
                {
                    b.Navigation("LqvNguoiDungs");

                    b.Navigation("LqvPhanQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
